# Base image
FROM spark:3.5.4-scala2.12-java11-ubuntu

# Set the user to root
USER root

# Install Python3, pip, and additional tools
RUN set -ex; \
    apt-get update; \
    apt-get install -y \
    python3 \
    python3-pip \
    iproute2 \           
    iputils-ping \       
    net-tools \          
    nano; \              
    rm -rf /var/lib/apt/lists/*

CMD ["tail", "-f", "/dev/null"]
