---
- name: Destroy terraform infrastructure host A (local)
  hosts: localhost
  tasks:
    - name: Destroy Terraform
      ansible.builtin.shell:
        cmd: terraform destroy -auto-approve
        chdir: /tmp/spoon_project/


- name: Destroy terraform infrastructure host B (remote)
  hosts: remote_host
  tasks:
    - name: Destroy Terraform
      ansible.builtin.shell:
        cmd: terraform destroy -auto-approve
        chdir: /tmp/spoon_project/