---
- name: Master Playbook for WordCount
  hosts: master
  become: yes
  tasks:
    - name: Diviser le texte en partitions
      command: split -n l/{{ groups['workers'] | length }} /tmp/input.txt /tmp/partition_
      args:
        chdir: /tmp

    - name: Copier les partitions vers les workers
      copy:
        src: "/tmp/partition_{{ item }}"
        dest: "/tmp/partition.txt"
      with_indexed_items: "{{ groups['workers'] }}"
      delegate_to: "{{ item.0 }}"
      run_once: true

    - name: Lancer le WordCount sur les workers
      command: python3 /tmp/wordcount.py /tmp/partition.txt
      register: worker_results
      delegate_to: "{{ item }}"
      with_items: "{{ groups['workers'] }}"

    - name: Collecter les résultats des workers
      debug:
        msg: "Worker {{ item.item }} result: {{ item.stdout }}"
      with_items: "{{ worker_results.results }}"
