---
- name: Worker Setup Playbook
  hosts: workers
  become: yes
  tasks:
    - name: Installer Python
      apt:
        name: python3
        state: present

    - name: Déployer le script WordCount
      copy:
        src: ./wordcount.py
        dest: /tmp/wordcount.py
        mode: '0755'
