---
- name: Automatiser le WordCount
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer Python
      apt:
        name: python3
        state: present

    - name: Créer le fichier d'entrée pour le WordCount
      copy:
        dest: /tmp/input.txt
        content: |
          hello world
          ansible automates tasks
          hello ansible

    - name: Déployer le script WordCount
      copy:
        src: ./wordcount.py
        dest: /tmp/wordcount.py
        mode: '0755'

    - name: Exécuter le WordCount
      command: python3 /tmp/wordcount.py /tmp/input.txt
      register: wordcount_result

    - name: Afficher le résultat du WordCount
      debug:
        msg: "{{ wordcount_result.stdout }}"
