---
- name: Deploy Docker containers using Terraform
  hosts: localhost
  tasks:
    # 1. Exécuter Terraform localement
    - name: Init terraform host
      command: terraform -chdir=/Users/victor/Documents/N7/ProjetInfrastructure/Projet_infra_3A_SN/victor/intern init

    - name: Apply Terraform on the local machine
      command: terraform -chdir=/Users/victor/Documents/N7/ProjetInfrastructure/Projet_infra_3A_SN/victor/intern apply -var="is_master=true" -auto-approve

- name: Deploy Docker containers using Terraform
  hosts: localhost
  tasks:
    # Copier le projet Terraform sur la machine distante avec scp
    - name: Copy Terraform project to the remote machine using scp
      command: scp -r -i ~/.ssh/id_rsa /Users/victor/Documents/N7/ProjetInfrastructure/Projet_infra_3A_SN/victor/intern/ root@172.20.10.6:/tmp/terraform_project/

- name: Deploy Docker containers using Terraform
  hosts: remote_host
  tasks:
    # Exécuter Terraform sur la machine distante
    - name: Execute Terraform on the remote machine
      command: terraform -chdir=/tmp/terraform_project/intern/ init

    - name: Apply Terraform on the remote machine
      command: terraform -chdir=/tmp/terraform_project/intern/ apply -var="is_master=false" -auto-approve -lock=false
