#cloud-config
users:
  - name: ubuntu
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7661M97CH5HaGJlULTXsBn/xCGTJfUdAk2paGd/JtVqWPDZ13U8qH/DCwvi9zrpLgsFArYrc4ue4FxidG2Ne5Ul+LSTlOp+fL3GqGyJnRkrKD54Xd+lDrmuZ0vOC+msVdTc7YCVgW+hSgH4TOBpz61hyNm2naqABksOQFpS4mqlHqxLNSvTLhgQtlzQr+vhYMZoVFCGAMXN8tFdPqeKzxeCbmVOPsI/wPd4UXnJhu5plBID3jdr7DypB481faK5fyVmlXQtmTeKSZsaOX5UglB4Ldx+7+mNRh1O5raa9ABOaNDHwU8+doZwuPuqi/FX6KuCtvcyv6bHi0Oyu/Poyj+ACP1MVQzP788PGGS8MYCky0uxLP85k2kf1mSAVknGpKJPfer72Ma2nc04GH1XobtEMYvGozti2p2UkbsUngBgitBDiOk5wo/24PsM7jYgHPjfj4tKKKwLrmzd8bugwqIZXA6mjynduEa1qf0rod/YU/hRzRNcKArOyVknmNZGHTGNO1wdkUojnICFK7+CnhVcE8EQY6eCTEmaZcksJ7RTmbaq5Q2hRJvFyxuTH79jv4wGXsSxAOFlUsWwFfReZFZ6r0BHahbJP/mHV+f5Aw0+twTDLCsGbLxnd6oS1GlmEk4Lr157JgsiOmrLsl6i/h4zHtROPhN5EBu4oT1WECrQ==    
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

password: ubuntu
chpasswd:
  expire: false
ssh_pwauth: true
packages:
  - qemu-guest-agent

network:
  version: 2
  ethernets:
    ens3:
      dhcp4: true