- name: Manage WordCount in VM
  hosts: all
  become: yes
  tasks:
    - name: Compile WordCount Java program
      shell: /home/ubuntu/compile_wordcount.sh
      args:
        executable: /bin/bash

    - name: Create WordCount JAR file
      shell: /home/ubuntu/create_jar.sh
      args:
        executable: /bin/bash

    - name: Run WordCount program
      shell: /home/ubuntu/run_wordcount.sh
      args:
        executable: /bin/bash