---
- name: Install PySpark on Nginx Container
  hosts: nginx
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PySpark using pip
      pip:
        name: pyspark
        executable: python3

    - name: Verify PySpark installation
      command: python3 -c "import pyspark; print(pyspark.__version__)"
      register: pyspark_version

    - name: Print PySpark version
      debug:
        msg: "PySpark version: {{ pyspark_version.stdout }}"
